"""
Django settings for pulse project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

All deploy-specific values come from environment variables (12-factor).
Defaults are safe for production: DEBUG is off unless explicitly enabled and a
SECRET_KEY must be supplied when DEBUG is off.
"""

import os
from pathlib import Path

import dj_database_url
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None or value.strip() == "":
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


def env_int(name: str, default: int) -> int:
    value = os.environ.get(name, "").strip()
    return int(value) if value else default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-development-only-key-do-not-use-in-production"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set when DEBUG is off. "
            "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(50))\""
        )

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# API Documentation (Swagger/ReDoc). Docs are public; the API itself requires a key.
ENABLE_DOCS = env_bool("ENABLE_DOCS", True)

# Admin is mounted at a configurable path to reduce drive-by brute forcing.
ADMIN_URL = os.environ.get("ADMIN_URL", "admin/").strip("/") + "/"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "notifications",
]

# Conditionally add drf-spectacular for API docs
if ENABLE_DOCS:
    INSTALLED_APPS.append("drf_spectacular")


MIDDLEWARE = [
    # Health checks answer before host validation / SSL redirect so that
    # load balancers and k8s probes (which use the pod IP as Host) always work.
    "pulse.health.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pulse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pulse.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=env_int("DB_CONN_MAX_AGE", 60),
        conn_health_checks=True,
    )
}


# Redis (used by the rate limiter, cache and - by default - the Celery broker)
REDIS_URL = os.environ.get(
    "REDIS_URL", os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {"socket_connect_timeout": 2, "socket_timeout": 2},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Served by WhiteNoise so the admin works with DEBUG off and no extra web server.

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# Security (effective when DEBUG is off)
# =============================================================================

# Set TRUST_X_FORWARDED_PROTO=true only when running behind a reverse proxy /
# PaaS router that sets X-Forwarded-Proto (Caddy, nginx, Render, Fly, ...).
if env_bool("TRUST_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = "DENY"
DATA_UPLOAD_MAX_MEMORY_SIZE = 256 * 1024  # API payloads are small JSON bodies


# =============================================================================
# API
# =============================================================================

# Comma-separated list of accepted API keys. Clients send `X-API-Key: <key>`
# (or `Authorization: Api-Key <key>`). If empty, the API is open ONLY when
# DEBUG is on; with DEBUG off every request is rejected (fail closed).
PULSE_API_KEYS = env_list("PULSE_API_KEYS")

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "notifications.authentication.APIKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "notifications.authentication.HasAPIKeyOrDevMode",
    ],
    "UNAUTHENTICATED_USER": None,
}

# Optional per-client (IP) throttle across the whole API, e.g. "300/min".
API_THROTTLE_RATE = os.environ.get("API_THROTTLE_RATE", "").strip()
if API_THROTTLE_RATE:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = ["rest_framework.throttling.AnonRateThrottle"]
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {"anon": API_THROTTLE_RATE}

# Add schema class if docs are enabled
if ENABLE_DOCS:
    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"

# drf-spectacular settings for OpenAPI/Swagger
SPECTACULAR_SETTINGS = {
    "TITLE": "Pulse Notification API",
    "DESCRIPTION": "A scalable notification and background job orchestration system. "
    "Supports multi-channel delivery (email, SMS, push), retries with exponential backoff, "
    "idempotency keys, rate limiting, and priority queues.",
    "VERSION": "1.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CONTACT": {
        "name": "Pulse API Support",
        "email": "pulse@shyamk.red",
    },
    "LICENSE": {
        "name": "MIT",
    },
    "TAGS": [
        {"name": "Notifications", "description": "Send and manage notifications"},
        {"name": "Templates", "description": "Notification template management"},
    ],
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
}

# Notification behaviour
RATE_LIMIT_ENABLED = env_bool("RATE_LIMIT_ENABLED", True)
RATE_LIMIT_MAX_REQUESTS = env_int("RATE_LIMIT_MAX_REQUESTS", 10)
RATE_LIMIT_WINDOW_SECONDS = env_int("RATE_LIMIT_WINDOW_SECONDS", 60)
NOTIFICATION_MAX_RETRIES = env_int("NOTIFICATION_MAX_RETRIES", 5)
NOTIFICATION_RETRY_BASE_DELAY = env_int("NOTIFICATION_RETRY_BASE_DELAY", 60)
HIGH_PRIORITY_TEMPLATE_KEYWORDS = env_list(
    "HIGH_PRIORITY_TEMPLATE_KEYWORDS", "otp,verification,verify,2fa"
)
LOG_RETENTION_DAYS = env_int("LOG_RETENTION_DAYS", 30)


# =============================================================================
# Celery
# =============================================================================

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Nothing reads task return values; state lives in NotificationLog.
CELERY_TASK_IGNORE_RESULT = True
CELERY_RESULT_EXPIRES = 3600
# Every worker consumes high_priority and/or low_priority; never the implicit
# "celery" queue (which no k8s worker listened to).
CELERY_TASK_DEFAULT_QUEUE = "low_priority"
# Reliability: ack after execution so a crashed worker's task is redelivered.
# Tasks are idempotent (they skip already-sent notifications).
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = env_int("CELERY_TASK_SOFT_TIME_LIMIT", 60)
CELERY_TASK_TIME_LIMIT = env_int("CELERY_TASK_TIME_LIMIT", 90)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Must exceed the longest retry countdown, or ETA tasks get redelivered early.
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}
CELERY_WORKER_SEND_TASK_EVENTS = True  # Flower
CELERY_TASK_SEND_SENT_EVENT = True

# Celery Beat for scheduling (in-memory/file-based scheduler)
CELERY_BEAT_SCHEDULE = {
    "cleanup-old-logs": {
        "task": "notifications.tasks.cleanup_old_logs",
        "schedule": crontab(hour=2, minute=0),  # Daily at 2 AM
        "args": (LOG_RETENTION_DAYS,),  # days_old
    },
    "send-daily-digest": {
        "task": "notifications.tasks.send_daily_digest",
        "schedule": crontab(hour=9, minute=0),  # 9 AM daily
        "args": (),
    },
}


# =============================================================================
# Delivery providers
# =============================================================================

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "pulse@shyamk.red")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = env_int("EMAIL_PORT", 1025)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
# Without a timeout a stuck SMTP server blocks a worker slot forever.
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 10)

# Twilio settings for SMS
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "").strip()
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "").strip()
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER", "").strip()

# Push: "console" logs and marks as sent (simulated, flagged in provider_config);
# "fcm" sends through Firebase Cloud Messaging.
PUSH_BACKEND = os.environ.get("PUSH_BACKEND", "console").strip().lower()
FIREBASE_CREDENTIALS_FILE = os.environ.get("FIREBASE_CREDENTIALS_FILE", "").strip()


# =============================================================================
# Logging (stdout by default; optional access-log file)
# =============================================================================

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
ACCESS_LOG_FILE = os.environ.get("ACCESS_LOG_FILE", "").strip()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
        "access": {
            "format": "%(asctime)s [%(levelname)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "pulse.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if ACCESS_LOG_FILE:
    Path(ACCESS_LOG_FILE).parent.mkdir(parents=True, exist_ok=True)
    LOGGING["handlers"]["app_file"] = {
        "level": "INFO",
        "class": "logging.handlers.WatchedFileHandler",
        "filename": ACCESS_LOG_FILE,
        "formatter": "access",
    }
    LOGGING["loggers"]["pulse.access"]["handlers"].append("app_file")
